build:
  cuda_version: "12.9"
  python_version: "3.10"
  system_packages:
    - "git"
  python_packages:
    - "torch"
  run:
    - "git clone https://huggingface.co/spaces/dangthr/PartPacker && cd PartPacker && pip install -r requirements.txt"
